### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by kblumenstein** [fhstp-mfg/mobilot#127] opened 2016-10-15 20:03 UTC
When logging in with kblumenstein3. I am the owner of the Mobidul Smart Inspection (as shown in My Mobiduls), but I do not see the admin area in the menu.
When logged out or with logged in admin, there are is shown the admin area (all stations, new station & settings) for this Mobidul.

**Comment by kblumenstein** [comment] 2016-10-15 20:09
It was not the first time, I had this problem, but at the moment I can not reproduce it.

**Comment by josephmiclaus** [comment] 2016-10-17 08:50
@kblumenstein possible duplicate of / same issue as #107

**Comment by doomsayer2** [comment] 2016-10-28 07:37
It is a duplicate of that issue indeed. The problem can be solved if you have logged in, than go to "All Mobiduls" and there on another mobidul or reload there the page, this should destroy the watcher. Than you can go in your mobidul and the admin area is back agian.

**Closed as completed by doomsayer2** 2016-10-28 07:37 UTC
Labels: bug, duplicate, high priority
